In [23]:
import numpy as np
import pandas as pd

Numpy Questions

In [3]:
# 1. Define two custom numpy arrays, say A and B. 
# Generate two new numpy arrays by stacking A and B vertically and horizontally.
A = np.array([1,2,3])
B = np.array([4,5,6])

C = np.vstack((A,B))
D = np.hstack((A,B))

print(C)
print(D)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [4]:
#2. Find common elements between A and B. [Hint : Intersection of two sets]
A = np.array([1,2,3,4])
B = np.array([4,5,6])

print(np.intersect1d(A,B))

[4]


In [11]:
#3. Extract all numbers from A which are within a specific range. eg between 5 and 10. 
# [Hint: np.where() might be useful or boolean masks]

A = np.arange(0,28,1)

A[np.where((A>5) & (A<20))]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
#4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[iris_2d[:,3]>1.5]

array([[6.3, 3.3, 4.7, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2

Pandas Questions

In [25]:
#5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.iloc[::20]


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
20     Chrysler  LeBaron  Compact       14.5   15.8       17.1      23.0   
40        Honda  Prelude   Sporty       17.0   19.8       22.7      24.0   
60      Mercury   Cougar  Midsize       14.9   14.9       14.9      19.0   
80       Subaru   Loyale    Small       10.5   10.9       11.3      25.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
20         28.0  Driver & Passenger      Front  ...        6.0   183.0   
40         31.0  Driver & Passenger      Front  ...        4.0   175.0   
60         26.0                None       Rear  ...        5.0   199.0   
80         30.0                None        4WD  ...        5.0   175.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
20      104.0   68.0         41.0           30.5          14.0  3085.0   
40      100.0   70.0         39.0           23.5           8.0  2865.0   
60      113.0   73.0         38.0           28.0          15.0  3610.0   
80       97.0   65.0         35.0           27.5          15.0  2490.0   

     Origin              Make  
0   non-USA     Acura Integra  
20      USA  Chrysler LeBaron  
40  non-USA     Honda Prelude  
60      USA    Mercury Cougar  
80  non-USA     Subaru Loyale  

[5 rows x 27 columns]

In [30]:

#6. Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace = True)

df['Min.Price'].isna().sum()

0

In [38]:
#7. How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df['row_sums'] = df.sum(axis=1)
print(df[df['row_sums']>100])

     0   1   2   3  row_sums
0   20  36  27  20       103
1   17  23  37  24       101
6   31  26  23  35       115
10  15  30  32  28       105
12  32  19  34  27       112
